-- Add exercises that were previously only in the native client migrations
INSERT INTO exercises (id, name, muscle_group, is_global) VALUES
  ('ex-031', 'Bulgarian Split Squat', 'Legs', true),
  ('ex-032', 'Hip Thrust', 'Legs', true),
  ('ex-033', 'Walking Lunge', 'Legs', true),
  ('ex-034', 'Hack Squat', 'Legs', true),
  ('ex-035', 'Goblet Squat', 'Legs', true),
  ('ex-036', 'Seated Leg Curl', 'Legs', true),
  ('ex-037', 'Sumo Deadlift', 'Legs', true),
  ('ex-038', 'Chin-Up', 'Back', true),
  ('ex-039', 'Single Arm Dumbbell Row', 'Back', true),
  ('ex-040', 'T-Bar Row', 'Back', true),
  ('ex-041', 'Straight Arm Pulldown', 'Back', true),
  ('ex-042', 'Back Extension', 'Back', true),
  ('ex-043', 'Rack Pull', 'Back', true),
  ('ex-044', 'Dumbbell Bench Press', 'Chest', true),
  ('ex-045', 'Incline Barbell Press', 'Chest', true),
  ('ex-046', 'Decline Bench Press', 'Chest', true),
  ('ex-047', 'Pec Deck', 'Chest', true),
  ('ex-048', 'Chest Dip', 'Chest', true),
  ('ex-049', 'Cable Fly', 'Chest', true),
  ('ex-050', 'Overhead Dumbbell Press', 'Shoulders', true),
  ('ex-051', 'Front Raise', 'Shoulders', true),
  ('ex-052', 'Cable Lateral Raise', 'Shoulders', true),
  ('ex-053', 'Upright Row', 'Shoulders', true),
  ('ex-054', 'Barbell Shrug', 'Shoulders', true),
  ('ex-055', 'Tricep Cable Extension', 'Arms', true),
  ('ex-056', 'EZ Bar Curl', 'Arms', true),
  ('ex-057', 'Preacher Curl', 'Arms', true),
  ('ex-058', 'Cable Curl', 'Arms', true),
  ('ex-059', 'Overhead Tricep Extension', 'Arms', true),
  ('ex-060', 'Close Grip Bench Press', 'Arms', true),
  ('ex-061', 'Incline Dumbbell Curl', 'Arms', true),
  ('ex-062', 'Crunch', 'Core', true),
  ('ex-063', 'Russian Twist', 'Core', true),
  ('ex-064', 'Hanging Leg Raise', 'Core', true),
  ('ex-065', 'Ab Wheel Rollout', 'Core', true),
  ('ex-066', 'Side Plank', 'Core', true),
  ('ex-067', 'Bicycle Crunch', 'Core', true)
ON CONFLICT (id) DO NOTHING;

-- Rename Overhead Press to Overhead Barbell Press
UPDATE exercises SET name = 'Overhead Barbell Press' WHERE id = 'ex-019' AND is_global = true;
