INSERT INTO exercises (id, name, muscle_group, is_global) VALUES
  ('ex-001', 'Barbell Back Squat', 'Legs', true),
  ('ex-002', 'Barbell Front Squat', 'Legs', true),
  ('ex-003', 'Leg Press', 'Legs', true),
  ('ex-004', 'Romanian Deadlift', 'Legs', true),
  ('ex-005', 'Leg Curl', 'Legs', true),
  ('ex-006', 'Leg Extension', 'Legs', true),
  ('ex-007', 'Calf Raise', 'Legs', true),
  ('ex-008', 'Barbell Deadlift', 'Back', true),
  ('ex-009', 'Pull-Up', 'Back', true),
  ('ex-010', 'Barbell Row', 'Back', true),
  ('ex-011', 'Cable Row', 'Back', true),
  ('ex-012', 'Lat Pulldown', 'Back', true),
  ('ex-013', 'Face Pull', 'Back', true),
  ('ex-014', 'Barbell Bench Press', 'Chest', true),
  ('ex-015', 'Incline Dumbbell Press', 'Chest', true),
  ('ex-016', 'Dumbbell Fly', 'Chest', true),
  ('ex-017', 'Cable Crossover', 'Chest', true),
  ('ex-018', 'Push-Up', 'Chest', true),
  ('ex-019', 'Overhead Press', 'Shoulders', true),
  ('ex-020', 'Lateral Raise', 'Shoulders', true),
  ('ex-021', 'Arnold Press', 'Shoulders', true),
  ('ex-022', 'Rear Delt Fly', 'Shoulders', true),
  ('ex-023', 'Barbell Curl', 'Arms', true),
  ('ex-024', 'Dumbbell Curl', 'Arms', true),
  ('ex-025', 'Hammer Curl', 'Arms', true),
  ('ex-026', 'Tricep Pushdown', 'Arms', true),
  ('ex-027', 'Skull Crusher', 'Arms', true),
  ('ex-028', 'Dips', 'Arms', true),
  ('ex-029', 'Plank', 'Core', true),
  ('ex-030', 'Cable Crunch', 'Core', true)
ON CONFLICT (id) DO NOTHING;
